## CAMBIA esto por el nombre de tu plugin.
name: DynaTech

## CAMBIA esto por tu nombre de usuario.
author: ProfElements

## CAMBIA esto por una descripción significativa pero corta de tu plugin.
description: Un addon de Slimefun que agrega cosas aleatorias que quiero

## CAMBIA esto por la ruta de la clase que extiende JavaPlugin.
main: me.profelements.dynatech.DynaTech

## Puedes cambiar esto para enlazar tu sitio web o repositorio. También puedes eliminar esta línea si lo deseas.
website: https://github.com/ProfElements/DynaTech

## Esto es obligatorio y marca a Slimefun como dependencia del plugin.
depend: [Slimefun]
softdepend: [ExoticGarden, InfinityExpansion, Gastronomicon]

## Este valor se reemplaza automáticamente por la versión especificada en tu archivo pom.xml, no lo cambies.
version: ${project.version}

## Esta es la versión mínima de Minecraft requerida para ejecutar tu plugin.
api-version: 1.19
